version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      - GITHUB_TOKEN=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
      - NEXT_PUBLIC_ENVIRONMENT=dev
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_GITHUB_AUTH_TOKEN=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
      - NEXT_PUBLIC_REPO_OWNER=0riion
      - NEXT_PUBLIC_REPO_NAME=commit-flow-history
    command: pnpm dev
